### ISSUE TITLE
Clipboard content with special characters results in incorrect output

### ISSUE THREAD

**Issue by 0009fe3** [leoobi/ClipTyper#1]
**Description of the bug:**

When the clipboard content that ClipTyper is supposed to type contains special characters, an incorrect character is sometimes written. For example, a "^" is incorrectly typed as "&".

**Steps to reproduce:**
Copy a text containing special characters (e.g., "^") to the clipboard.
Use ClipTyper to paste the copied text.
Observe the output.

**Expected behavior:**
The special characters in the clipboard should be typed correctly by ClipTyper.

**Actual behavior:**
Special characters such as "^" are replaced by incorrect characters like "&".

**Comment by leoobi** [comment]
The program should now successfully support the german keyboard layout
